Duration statistics revamp
simra-project/SimRa-Visualization pull request #84
Opened 2019-12-11 14:30 UTC by sehof-git

Added duration for rides and refactored statistics

2020-01-12 17:44 UTC, adriangronau requested changes
Die neue Implementation ist unvollständig:
- incidentCountWithTrailersInvolved hat einen falschen Wert (0)
- timestamp ist kein Unix-Timestamp mehr sondern ein String

Folgende Felder fehlen: 
- profileAgeDistributionData
- profileAgeDistributionDataMale
- profileAgeDistributionDataFemale
- profileAgeDistributionDataOther
- profileAgeGroupCrossData

2020-01-12 17:48 UTC, tharkay commented
[Previous JSON Response](https://github.com/simra-project/SimRa-Visualization/files/4050903/previous.txt)
[New JSON Response](https://github.com/simra-project/SimRa-Visualization/files/4050904/new.txt)

2020-01-21 20:42 UTC, sehof-git commented
- incidentCountWithTrailersInvolved hat in MongoDB auch den Wert 0. Läuft beim CSV Import vllt was falsch?
- Timestamp auf Long geändert
- Restliche Felder ergänzt

2020-01-28 19:02 UTC, sehof-git commented
profileAgeGroupCrossTotal/Data: Felder "accumulatedDuration" und "averageDuration" gefixt

2020-01-29 17:59 UTC, adriangronau approved these changes

2020-01-29 17:59 UTC, merged